region="us-east-1"
aws_profile = "default"
cidr_block = "10.0.0.0/16"
public_subnets_count = 2
private_subnets_count = 2
vpc_name = "management"
availability_zones = ["us-east-1a", "us-east-1b"]
bastion_instance_type = "t2.micro"
public_key = "/Users/max.santos/.ssh/id_rsa.pub"
